events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    upstream backend_upstream {
        server backend:3000;
    }

    server {
        listen 443 ssl;
        server_name film-rechkalov.nomorepartiessite.ru;

        ssl_certificate /etc/letsencrypt/live/film-rechkalov.nomorepartiessite.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/film-rechkalov.nomorepartiessite.ru/privkey.pem;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }

    server {
        listen 80;
        server_name film-rechkalov.nomorepartiessite.ru;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name api-film-rechkalov.nomorepartiessite.ru;

        ssl_certificate /etc/letsencrypt/live/film-rechkalov.nomorepartiessite.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/film-rechkalov.nomorepartiessite.ru/privkey.pem;

        location / {
            proxy_pass http://backend_upstream;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 80;
        server_name api-film-rechkalov.nomorepartiessite.ru;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 80;
        server_name localhost;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
}
